elysiajs/elysia-swagger

package.json, src/index.ts
This pull request addresses an issue where the Swagger plugin for ElysiaJS was not effectively merging custom components provided at the application level.
Example of the problem:
```typescript
export const swaggerConfig: ElysiaSwaggerConfig = {
documentation: {
info: {
title: "Endpoint Documentation",
version: "1.0.0",
description: "A very good description.",
},
components: {
schemas: {
User: {
description: "string",
},
},
securitySchemes: {
JwtAuth: {
type: "http",
scheme: "bearer",
bearerFormat: "JWT",
description: "Enter JWT Bearer token **_only_**",
},
},
},
},
};
``;
``` 
Would result on a /swagger/json like this:
```
{
"openapi": "3.0.3",
"info": {
"title": "Endpoint Documentation",
"description": "A very good description.",
"version": "1.0.0"
},
"components": {
"schemas": {
} ❌ …
```
=> Fix: Swagger Component Integration

src/utils.ts, test/index.test.ts
This merge request addresses an issue that was wrongly opened in the elysia repository: https://github.com/elysiajs/elysia/issues/124
Using responses types like `t.Void()`, `t.Undefined()` or `t.Null()` means that in fact there will be no content in the response.
It could happen in a scenario of status code 204, when no respose is expected.
But current behaviour is breaking the view, since it generates a response with a content that is not acceptable by swagger:
An example:
Code:
```javascript
{
body: "ActivationUserRequest",
response: {
200: t.Void({
description: "User account was activated successfully",
}),
404: t.Void({
description: "Pending account confirmation was not found",
}),
409: t.Void({
description: "Account was already confirmed",
}),
},
detail: {
description:
"Activate a …
```
=> feat: handle nullish response types

src/index.ts
Hi, I fixed a veeery slight typo in the default documentation description. I can't help but I notice it too much lol. Thanks
=> fix: typo in default documentation description

src/index.ts
Hi! This PR bumps the default Swagger-UI version from 5.7.2 to 5.9.0.
=> chore: Update Swagger-UI

.npmignore, package.json
The current config results in the dependent package compiling this package, which works in most cases but can fail if the dependent package has an incompatible `tsconfig.json`, e.g. by applying stricter options such as `exactOptionalPropertyTypes`.
This PR should bring the package in-line with the standard way of doing this, making sure it works for all `tsconfig.json` settings. It looks like a similar change was already made in the main `elysia` package as part of [this commit](https://github.com/elysiajs/elysia/commit/8c8ffa53ef5952f1f4613c4f40f197adee323457).
=> Point package.json "types" field to generated .d.ts instead of raw .ts

src/index.ts
I have a reverse proxy which serves my Elysia API at a subpath and it causes the swagger UI to fail loading the swagger JSON. Using relative URL fixes that.
=> use relative path to swagger json

README.md
Readme example is missing an import of t:JavaScriptTypeBuilder and does not work copy-pasted to a new project.
=> Fixed missin JavaScriptTypeBuilder import

src/index.ts, src/types.ts
This gets rid of options displaying in the generated swagger, useful when using for example the CORS plugin when you have several options routes. Note: by default I set it to true as I believe very few people would want CORS in their swagger.
=> add exclude options

src/index.ts, src/scalar/index.ts, src/types.ts
Currently the URL to the scalar bundle is hardcoded to the [jsdeliver.net](https://cdn.jsdelivr.net) CDN. This PR added an additional option (`scalarCDN`) so the URL to the scalar bundle can be explicitly set. This is useful if a user wishes to host the scalar bundle themselves. When the `scalarCDN` option is set, the `scalarVersion` is ignored.
This change maintains backwards compatibility, and users who have `scalarVersion` set, will still get the scalar bundle from the default [jsdelivr.net](https://cdn.jsdelivr.net) CDN.
Example usage:
```javascript
const server = new Elysia().use(html).use(
swagger({
provider: "scalar",
scalarCDN: "https://unpkg.com/@scalar/api-reference@1.13.10/dist/browser/standalone.js"
//scalarCDN: "/public/standalone.min.js" //Served locally
})
);
```
=> Scalar CDN Option

src/index.ts, src/scalar/index.ts, src/types.ts
lot's of great fixes in v1.13.0!
```
97cd84e9: feat: client ignore list
5dac9c51: fix: open section on search result click
0e0f34b3: fix: cleanup safari bugs
7582e82a: fix: classic layout stylings
d5d55407: feat: expose dark mode light mode property in config
7d502131: fix: add markdown rendering for body schema
3e7c4cf7: feat: add fetch examples
859977f8: feat: Add dynamic content type selection for request body
0b66933d: fix: declare theme font for buttons and fix regressed font weight
87ed7f01: fix: markdown second level margin issue
4513c725: feat: add intro flare for gradients
```
=> fix: update scalar to v1.13.0

src/index.ts
Little fix in the documentation get-route
Should render properly on the browser
Let me know if more is needed!
Fixes #98
=> 🔧 fix: doc get-route not rendering

src/utils.ts
You can see below that `type` is removed from `rest` using the destructure syntax.
https://github.com/elysiajs/elysia-swagger/blob/12ec0e11d1a10443b1d78f26c6771022335b6825/src/utils.ts#L182-L208
=> fix: use `type` variable since `rest.type` is always undefined

src/utils.ts
The `patternProperties` must be placed beside the `type: "object"` property to be properly supported by other tools. Before this commit, it was being placed beside the `content` property of a ResponseObject.
=> fix: include patternProperties in object schema

example/plugin.ts, src/utils.ts, test/validateSchema.test.ts
- resolves #102
- Leave `description` and `examples` as parameter keywords, while move others to schema keywords. Based on:
- https://swagger.io/specification/#parameter-object 
- https://swagger.io/docs/specification/data-models/keywords/
- https://swagger.io/docs/specification/describing-parameters/
- Added simple example and testing
=> Move parameters schema keywords location

example/index3.ts, src/index.ts
This PR resolves an issue related to path options.
The reason as to why is the following scenario:
I use trpc with Elysia.js, my goal is now to include Swagger documentation of that process.
Below is my personal usecase / way as in how I generate the trpc documentation and how I use it.
```ts
import { trpc } from "@elysiajs/trpc";
import { Elysia } from "elysia";
import { appRouter } from "./router/router";
import { swagger } from "@elysiajs/swagger";
import {
generateOpenApiDocument,
} from "trpc-openapi";
export const openApiDocument = generateOpenApiDocument(appRouter, {
title: "tRPC OpenAPI",
version: "1.0.0",
baseUrl: "http://localhost:3000",
});
const swaggerExec = swagger({
documentation: {
paths: openApiDocument.paths,
},
});
const app = new Elysia()
.use(
trpc(appRouter, { …
```
=> bugfix(accept external swagger paths)

src/index.ts, src/types.ts
Hi everyone I added a new parameter to exclude tags. Currently we can exclude the endpoints but we can't exclude tags. Example: https://api.exchangeratesapi.net/docs
=> feature: exclude tags

src/index.ts, test/index.test.ts, test/validate-schema.test.ts
This adds support for `app.all()` by simply registering a path for each allowed method in the OpenAPI Specification.
(As a side effect, this will also filter out any method that's not in the specification.)
closes #47, closes #130
=> Add Support for app.all()

src/index.ts
This PR fixes the issue reported on https://github.com/elysiajs/elysia-swagger/issues/135
=> Fix nested path issue in Swagger and Scalar config

src/utils.ts
Close #155.
Hooks might be strings and might be accidentally deconstructed in cloneHook. This will break schemas defined in models.
output of 1.1.4
```
"application/json": {
"schema": {
"0": "a",
"1": "u",
"2": "t",
"3": "h",
"4": ":",
"5": ":",
"6": "s",
"7": "i",
"8": "g",
"9": "n"
}
}
```
output of 1.1.3
```
"application/json": {
"schema": {
"$ref": "#/components/schemas/auth::sign"
}
}
```
=> Add type check in cloneHook

src/index.ts
There was a regression introduced with **Fix nested path issue in Swagger and Scalar config #146** which was meant to fix #135, when `path` is either `"/"` or `""` it leads to `Failed to fetch spec from URL` or `ERR_NAME_NOT_RESOLVED` because the `url` becomes `"http://json/"`. 
I can create a new issue but it might address #151
I also noticed that `excludePaths` might not be working as intended for when `path` is either `"/"` or `""` but that's always been the behavior so I didn't address that.
=> fix: 🐛 prevent failed to fetch spec from URL error

src/index.ts
When using a prefix, the plugin tries to fetch the scalar config from an incorrect path as mentioned in issues #161, #183, #151 . This can be seen in the screenshots below.
This PR enables successful fetching of the Scalar config from the correct URL whether a prefix is used or not and even if the prefix is nested.
closes #161 
closes #183 
closes #151 
closes #157
=> Fix path issue in Scalar config
